name: Update News Articles

on:
  schedule:
    # Runs every hour
    # For more schedule options, see: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser

    - name: Run the RSS to JSON script
      run: python rss_to_json.py

    - name: Commit and push changes
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add articles.json
        git commit -m 'Update news articles [skip ci]' || echo "No changes to commit"
        git push